[tool.poetry]
name = "bollywood-movie-picker"
version = "0.1.0"
description = ""
authors = ["Mihir Kurdekar <mihir.kurdekar@gmail.com>"]
readme = "README.md"
packages = [{include = "bollywood_movie_picker"}]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"
# all dependencies below to be commented while serverless deploy
#pandas = "^2.2.2"
#beautifulsoup4 = "^4.12.3"
#requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
